const APP_VERSION='V1.2.0';
const GOOGLE_API_URL='https://script.google.com/a/macros/ichc.ro/s/AKfycbzDAauThmGXzKtRIYZMbgutyJI3XO_r5uRLuLhqTG8putr6wpGcfE38_dmYmdEi9XY/exec';
const OCR_API_URL='https://math-max-mlb-poems.trycloudflare.com/health';
let scanMode='screen',cameraStream=null,videoDevices=[],currentDeviceId=null,ocrBusy=false,macConfirmed=false;

document.addEventListener('DOMContentLoaded',async()=>{setScanMode('screen');resetMacState();loadDashboard();await discoverCameras();checkOCRServer();});

async function checkOCRServer(){if(OCR_API_URL.includes('PASTE_YOUR')){setOCRServerState(false,'Configure OCR_API_URL in app.js');return;}try{const r=await fetch(OCR_API_URL+'/health',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();setOCRServerState(!!d.success,d.success?'PaddleOCR online • '+d.version:'OCR server offline');}catch(e){console.error(e);setOCRServerState(false,'OCR server offline');}}
function setOCRServerState(ok,msg){const p=document.getElementById('ocrServerPanel');p.classList.remove('serverOnline','serverOffline');p.classList.add(ok?'serverOnline':'serverOffline');document.getElementById('ocrServerText').textContent=msg;setSystemStatus(ok?'OCR ready':'OCR offline',ok);}
function setScanMode(mode){scanMode=mode==='label'?'label':'screen';const s=document.getElementById('screenModeBtn'),l=document.getElementById('labelModeBtn'),f=document.getElementById('scanFrame');s.classList.toggle('active',scanMode==='screen');l.classList.toggle('active',scanMode==='label');f.classList.toggle('screenFrame',scanMode==='screen');f.classList.toggle('labelFrame',scanMode==='label');document.getElementById('modeHint').textContent=scanMode==='screen'?'Optimized for MAC addresses displayed on screens.':'Use for stickers, printers, access points and device labels.';}
async function discoverCameras(){try{const d=await navigator.mediaDevices.enumerateDevices();videoDevices=d.filter(x=>x.kind==='videoinput');populateCameraList();}catch(e){showMessage('Camera not supported.','error');}}
function populateCameraList(){const s=document.getElementById('cameraSelect'),r=document.getElementById('cameraSelectRow');s.innerHTML='';if(!videoDevices.length){r.classList.add('hidden');return;}videoDevices.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Camera '+(i+1);s.appendChild(o);});r.classList.remove('hidden');}
async function startCamera(id=null){try{stopCamera();const v=document.getElementById('camera');const c={width:{ideal:1920},height:{ideal:1080}};if(id)c.deviceId={exact:id};else c.facingMode={ideal:'environment'};cameraStream=await navigator.mediaDevices.getUserMedia({video:c,audio:false});v.srcObject=cameraStream;await v.play();document.getElementById('cameraPlaceholder').classList.add('hidden');document.getElementById('scanBtn').disabled=false;document.getElementById('switchCameraBtn').disabled=false;document.getElementById('startCameraBtn').textContent='RESTART CAMERA';currentDeviceId=cameraStream.getVideoTracks()[0].getSettings().deviceId||null;await discoverCameras();document.getElementById('cameraSelect').value=currentDeviceId||'';}catch(e){showMessage('Camera error: '+e.message,'error');}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}}
async function changeCamera(){const v=document.getElementById('cameraSelect').value;if(v)await startCamera(v);}
async function switchCamera(){if(videoDevices.length<2){showMessage('Only one camera available.','warning');return;}let i=videoDevices.findIndex(d=>d.deviceId===currentDeviceId)+1;if(i>=videoDevices.length)i=0;await startCamera(videoDevices[i].deviceId);}
function captureCameraFrame(){const v=document.getElementById('camera'),c=document.getElementById('scanCanvas'),x=c.getContext('2d');const w=v.videoWidth,h=v.videoHeight,cw=w*.92,ch=h*(scanMode==='screen'?.32:.62),sx=(w-cw)/2,sy=(h-ch)/2,scale=1.8;c.width=Math.round(cw*scale);c.height=Math.round(ch*scale);x.drawImage(v,sx,sy,cw,ch,0,0,c.width,c.height);return c;}
async function scanMac(){if(ocrBusy)return;const v=document.getElementById('camera');if(!v.videoWidth){showMessage('Camera is not ready.','warning');return;}await sendCanvasToOCR(captureCameraFrame());}
function scanUploadedPhoto(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{const img=new Image();img.onload=async()=>{const c=document.getElementById('scanCanvas'),x=c.getContext('2d');let w=img.width,h=img.height,m=2400;if(Math.max(w,h)>m){const q=m/Math.max(w,h);w=Math.round(w*q);h=Math.round(h*q);}c.width=w;c.height=h;x.drawImage(img,0,0,w,h);await sendCanvasToOCR(c);};img.src=ev.target.result;};r.readAsDataURL(f);}
function canvasToBlob(c){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Could not create image.')),'image/jpeg',.95));}
async function sendCanvasToOCR(c){if(OCR_API_URL.includes('PASTE_YOUR')){showMessage('OCR_API_URL is not configured.','error');return;}ocrBusy=true;document.getElementById('scanBtn').disabled=true;resetOCRResult();setOCRStatus(true,'PaddleOCR is reading...','Sending image to local OCR server');try{const b=await canvasToBlob(c),fd=new FormData();fd.append('image',b,'mac-scan.jpg');const r=await fetch(OCR_API_URL+'/ocr',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'OCR request failed');handleOCRResult(d);}catch(e){setOCRServerState(false,'OCR connection failed');showMessage('PaddleOCR error: '+e.message,'error');setMacState('invalid','OCR ERROR');}finally{ocrBusy=false;document.getElementById('scanBtn').disabled=false;setOCRStatus(false);}}
function handleOCRResult(d){setOCRServerState(true,'PaddleOCR online');if(!d.found||!d.candidates?.length){setMacState('invalid','MAC NOT FOUND');document.getElementById('macValidation').textContent='PaddleOCR read the image but no MAC pattern was detected.';showMessage('No MAC detected. Try a closer image.','warning');return;}renderCandidates(d.candidates);selectCandidate(d.candidates[0].mac);showMessage(d.candidates.length+' MAC candidate(s) detected in '+d.processingSeconds+' s.','success');}
function renderCandidates(a){const s=document.getElementById('candidateSection'),l=document.getElementById('candidateList');l.innerHTML='';a.forEach(c=>{const b=document.createElement('button');b.className='candidateBtn';b.innerHTML=escapeHtml(c.mac)+'<small>'+escapeHtml(c.votes+' OCR reading(s)'+(c.corrected?' • OCR correction used':''))+'</small>';b.onclick=()=>selectCandidate(c.mac);l.appendChild(b);});s.classList.remove('hidden');}
function selectCandidate(mac){document.getElementById('macInput').value=mac;macConfirmed=false;setMacState('candidate','OCR CANDIDATE');document.getElementById('macValidation').textContent='Compare this MAC with the device, then confirm it.';document.getElementById('confirmBtn').classList.remove('hidden');document.getElementById('saveBtn').disabled=true;}
function handleMacInput(){const i=document.getElementById('macInput');let c=i.value.toUpperCase().replace(/[^0-9A-F]/g,'').substring(0,12),g=[];for(let x=0;x<c.length;x+=2)g.push(c.substring(x,x+2));i.value=g.join(':');macConfirmed=false;const m=normalizeMac(i.value);document.getElementById('confirmBtn').classList.toggle('hidden',!m);document.getElementById('saveBtn').disabled=true;if(m){i.value=m;setMacState('candidate','VERIFY MAC');document.getElementById('macValidation').textContent='Valid format. Confirm the value before saving.';}}
function confirmMac(){const i=document.getElementById('macInput'),m=normalizeMac(i.value);if(!m){showMessage('Invalid MAC Address.','error');return;}i.value=m;macConfirmed=true;setMacState('valid','CONFIRMED');document.getElementById('macValidation').textContent='MAC verified and ready to save.';document.getElementById('confirmBtn').classList.add('hidden');document.getElementById('saveBtn').disabled=false;}
function normalizeMac(v){const c=String(v||'').toUpperCase().replace(/[^0-9A-F]/g,'');return /^[0-9A-F]{12}$/.test(c)?c.match(/.{2}/g).join(':'):null;}
function resetOCRResult(){macConfirmed=false;document.getElementById('candidateSection').classList.add('hidden');document.getElementById('candidateList').innerHTML='';document.getElementById('confirmBtn').classList.add('hidden');document.getElementById('saveBtn').disabled=true;}
function resetMacState(){resetOCRResult();document.getElementById('macInput').value='';document.getElementById('macValidation').textContent='';setMacState('waiting','Waiting for scan');}
function saveAndNext(){if(!macConfirmed){showMessage('Confirm the MAC Address first.','warning');return;}const m=normalizeMac(document.getElementById('macInput').value);if(!m)return;const b=document.getElementById('saveBtn');b.disabled=true;b.textContent='SAVING...';apiRequest({api:'v11',action:'saveMac',mac:m,device:document.getElementById('deviceType').value,location:document.getElementById('location').value,note:document.getElementById('note').value},r=>{b.textContent='SAVE & SCAN NEXT';if(r.success){document.getElementById('deviceCount').textContent=r.count;document.getElementById('note').value='';resetMacState();showMessage('Saved: '+r.mac,'success');loadDashboard();window.scrollTo({top:0,behavior:'smooth'});}else{b.disabled=false;showMessage(r.message||'Save failed.',r.type==='duplicate'?'warning':'error');}},()=>{b.textContent='SAVE & SCAN NEXT';b.disabled=false;});}
function loadDashboard(){apiRequest({api:'v11',action:'dashboard'},d=>{if(!d.success)return;document.getElementById('deviceCount').textContent=d.count||0;renderRecent(d.recent||[]);});}
function apiRequest(p,ok,err){if(GOOGLE_API_URL.includes('PASTE_YOUR')){showMessage('Google API URL is not configured.','error');return;}const cb='__macCallback_'+Date.now()+'_'+Math.floor(Math.random()*100000),s=document.createElement('script');let done=false;const to=setTimeout(()=>{if(done)return;done=true;clean();if(err)err();},15000);function clean(){clearTimeout(to);delete window[cb];if(s.parentNode)s.parentNode.removeChild(s);}window[cb]=d=>{if(done)return;done=true;clean();if(ok)ok(d);};p.callback=cb;s.src=GOOGLE_API_URL+'?'+new URLSearchParams(p).toString();s.onerror=()=>{if(done)return;done=true;clean();if(err)err();};document.body.appendChild(s);}
function renderRecent(items){const c=document.getElementById('recentList');if(!items.length){c.innerHTML='<div class="emptyState">No devices registered yet.</div>';return;}c.innerHTML=items.map(i=>'<div class="recentItem"><div class="recentTop"><div class="recentMac">'+escapeHtml(i.mac)+'</div><div class="recentDevice">'+escapeHtml(i.device||'Device')+'</div></div><div class="recentBottom"><span>'+escapeHtml(i.location||'No location')+'</span><span>'+escapeHtml(i.timestamp)+'</span></div></div>').join('');}
function setOCRStatus(show,title='',progress=''){const b=document.getElementById('ocrStatus');b.classList.toggle('hidden',!show);if(show){document.getElementById('ocrTitle').textContent=title;document.getElementById('ocrProgress').textContent=progress;}}
function setMacState(type,text){const s=document.getElementById('macState');s.className='macState '+type;s.textContent=text;}
function setSystemStatus(text,ready){const s=document.getElementById('systemStatus');s.innerHTML='<span class="statusDot"></span>'+escapeHtml(text);s.querySelector('.statusDot').style.background=ready?'#4cea92':'#ff7474';}
function showMessage(message,type){const b=document.getElementById('messageBox');b.className='messageBox '+(type==='success'?'messageSuccess':type==='warning'?'messageWarning':'messageError');b.textContent=message;b.classList.remove('hidden');setTimeout(()=>b.classList.add('hidden'),6000);}
function escapeHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
